reworked tutorial to fit current needs.
Innoactive/Hub-Tutorial-Unity-Project pull request #5
Opened 2019-06-25 08:39 UTC by LukasReindlGit

Updated tutorial to new needs

2019-06-25 09:24 UTC, tomwim requested changes
Only code review, havent checked project out yet

2019-06-25 09:24 UTC, tomwim commented on Assets/Scripts/DayNight/CustomLightSetupMenu.cs
> +            // Use Add(new ButtonItem(resourceIcon, (controller)=> { // Do something. })));
```suggestion
            // Use Add(new ButtonItem(resourceIcon, (controller) => { // Do something. })));
```

2019-06-25 09:24 UTC, tomwim commented on Assets/Scripts/DayNight/CustomLightSetupMenu.cs
> +
Empty line

2019-06-25 09:24 UTC, tomwim commented on Assets/Scripts/Flashlight/Battery/BatteryNetworking.cs
> +            // TODO Chapter 11: Add this component to the ObservedComponents list in the photonview.
```suggestion
            // TODO Chapter 11: Add this component to the ObservedComponents list in the PhotonView.
```

2019-06-25 09:24 UTC, tomwim commented on Assets/Scripts/Flashlight/Battery/BatteryPersistenceData.cs
> +    public class BatteryPersistenceData : PersistentProperty.PropData
Do we need docu here? Might make sense for the tutorial?

2019-06-25 09:24 UTC, tomwim commented on Assets/Scripts/Flashlight/Battery/BatteryPersistenceTranslator.cs
> +    public class BatteryPersistenceTranslator : SingleComponentPropertyTranslator<BatteryPersistenceData, Battery>
Do we need docu here? Might make sense for the tutorial?

2019-06-25 09:24 UTC, tomwim commented on Assets/Scripts/Flashlight/FlashlightContextMenu.cs
> +         ContextMenuItemDesign design = new ContextMenuItemDesign();
wrong indentation

2019-06-25 09:24 UTC, tomwim commented on Assets/Scripts/Flashlight/FlashlightNetworking.cs
> +
empty line

2019-06-25 09:24 UTC, tomwim commented on Assets/Scripts/Flashlight/FlashlightPeristenceTranslator.cs
> +        FlashlightPersistenceTranslator : SingleComponentPropertyTranslator<FlashlightPersistenceData, Flashlight>
weird line break

2019-07-01 14:24 UTC, LukasReindlGit commented on Assets/Scripts/Flashlight/FlashlightPeristenceTranslator.cs
> +        FlashlightPersistenceTranslator : SingleComponentPropertyTranslator<FlashlightPersistenceData, Flashlight>
wtf?

2019-07-09 08:26 UTC, tomwim approved these changes

2019-07-09 09:18 UTC, merged